# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 06:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=b'DEFAULT VALUE', max_length=100)),
                ('city', models.CharField(default=b'DEFAULT VALUE', max_length=30)),
                ('website', models.URLField(default=b'DEFAULT VALUE')),
                ('phone', models.IntegerField(default=b'0')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
