<<<<<<< HEAD
# Generated by Django 2.0 on 2018-01-01 07:46
=======
# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 22:09
from __future__ import unicode_literals
>>>>>>> 96c979f4222ce75b09611ebba7afe828e513e75d

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('description', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=18)),
                ('website', models.URLField(default='')),
                ('phone', models.IntegerField(default='0')),
=======
                ('description', models.CharField(default=b'', max_length=100)),
                ('city', models.CharField(default=b'', max_length=18)),
                ('website', models.URLField(default=b'')),
                ('phone', models.IntegerField(default=b'0')),
>>>>>>> 96c979f4222ce75b09611ebba7afe828e513e75d
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
