# Generated by Django 2.0 on 2018-01-01 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete='', to=settings.AUTH_USER_MODEL),
        ),
    ]
